version: 0.2

phases:
  install:
    commands:
      - echo "Installing prerequisites..."
      - yum install -y yum-utils

  pre_build:
    commands:
      - echo "Setting up Terraform..."
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform version

  build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Planning changes..."
      - terraform plan -out "tfplan"
      - echo "Applying changes..."
      - terraform apply -auto-approve "tfplan"

  post_build:
    commands:
      - echo "Deployment complete!"
      - echo "Web server URL: $(terraform output -raw web_url || echo 'No output')"