---
version: 0.2
phases:
  install:
    commands:
      - echo "Installing prerequisites..."
      - yum install -y yum-utils
  pre_build:
    commands:
      - echo "Setting up Terraform..."
      - yum-config-manager --add-repo  https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform version
      - echo $AWS_DEFAULT_REGION
      - export TF_VAR_region=$AWS_DEFAULT_REGION
  build:
    commands:
      - echo "Navgate to the project files"
      - cd app-terraform
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Planning changes..."
      - terraform plan -out "tfplan"
      - echo "Applying changes..."
      - terraform apply -auto-approve "tfplan"
  post_build:
    commands:
      - echo "Deployment complete!"
